---
#configuring web server

- name: deploying configuration file
  copy: src=apache2.conf dest=/etc/apache2/apache2.conf
  notify: restart apache


# Add sample html file
- name: deploy index.html
  copy:
   src: index.html
   dest: /var/www/html/index.html