---

 - hosts: dev
   tasks:
   - name: use argv to send the command as a list.  Be sure to leave command empty
     command: touch "{{ test_file }}"                   
     args:
       chdir: "{{ test_dir }}"
       creates: "{{ test_file }}"
       #chdir: /home/vikas/Documents/
       #creates: myfile1.txt
... 
